import 'package:flutter/material.dart';

import '../../../models/courses_planner_model.dart';

const List<PlannerCourse> dummyCourses = [
    PlannerCourse(
      id: 'cs301',
      code: 'CS301',
      title: 'Machine Learning',
      professor: 'Lee Meng Jiao',
      credits: 2,
      type: 'CORE',
      department: 'Computer Science',
      limit: 60,
      rating: 5.0,
      reviews: 128,
      midtermDate: 'Oct 15',
      finalDate: 'Dec 20',
      projectDate: 'Dec 10',
      grading: {'Exams': 40, 'Projects': 40, 'Participation': 20},
      syllabus: [
        'Introduction & Overview',
        'Core Concepts & Theory',
        'Practical Applications',
      ],
      timeSlot: 'Mon 11:10 - 14:10',
      slotCode: 'M4M5',
      location: 'Building B, Room 402',
      day: 1,
      startSlot: 3,
      duration: 2,
      color: Color(0xFF14B8A6),
    ),

    PlannerCourse(
      id: 'cs210',
      code: 'CS210',
      title: 'Computer Architecture',
      professor: 'Huang Wei Cheng',
      credits: 2,
      type: 'CORE',
      department: 'Computer Science',
      limit: 60,
      rating: 4.8,
      reviews: 96,
      midtermDate: 'Oct 20',
      finalDate: 'Dec 18',
      projectDate: 'Dec 5',
      grading: {'Exams': 50, 'Projects': 30, 'Participation': 20},
      syllabus: ['CPU Basics', 'Memory System', 'Instruction Pipeline'],
      timeSlot: 'Tue 08:00 - 09:50',
      slotCode: 'T1T2',
      location: 'Engineering Building, Room 205',
      day: 2,
      startSlot: 0,
      duration: 2,
      color: Color(0xFF60A5FA),
    ),

    PlannerCourse(
      id: 'math202',
      code: 'MATH202',
      title: 'Probability',
      professor: 'Chen Yi Ting',
      credits: 3,
      type: 'ELECTIVE',
      department: 'Mathematics',
      limit: 80,
      rating: 4.6,
      reviews: 77,
      midtermDate: 'Oct 18',
      finalDate: 'Dec 22',
      projectDate: 'None',
      grading: {'Exams': 70, 'Homework': 20, 'Participation': 10},
      syllabus: ['Counting', 'Random Variables', 'Expected Value'],
      timeSlot: 'Tue 13:20 - 15:10',
      slotCode: 'T5T6',
      location: 'General Building, Room 301',
      day: 2,
      startSlot: 5,
      duration: 2,
      color: Color(0xFFA855F7),
    ),

    PlannerCourse(
      id: 'lang101',
      code: 'LANG101',
      title: 'College Chinese',
      professor: 'Lin Mei Hua',
      credits: 2,
      type: 'LANGUAGE',
      department: 'Language',
      limit: 40,
      rating: 4.7,
      reviews: 88,
      midtermDate: 'Oct 12',
      finalDate: 'Dec 16',
      projectDate: 'None',
      grading: {'Exams': 50, 'Homework': 30, 'Participation': 20},
      syllabus: ['Reading Practice', 'Writing Practice', 'Final Presentation'],
      timeSlot: 'Thu 13:20 - 15:10',
      slotCode: 'R5R6',
      location: 'Language Center, Room 101',
      day: 4,
      startSlot: 5,
      duration: 2,
      color: Color(0xFFFBBF24),
    ),

    PlannerCourse(
      id: 'ge101',
      code: 'GE101',
      title: 'Modern Society and Culture',
      professor: 'Wang Shu Fen',
      credits: 2,
      type: 'GE',
      department: 'General Education',
      limit: 100,
      rating: 4.5,
      reviews: 64,
      midtermDate: 'Oct 17',
      finalDate: 'Dec 19',
      projectDate: 'Nov 30',
      grading: {'Exams': 40, 'Projects': 40, 'Participation': 20},
      syllabus: [
        'Society and Identity',
        'Culture and Media',
        'Final Group Report',
      ],
      timeSlot: 'Fri 09:00 - 09:50',
      slotCode: 'F2',
      location: 'Humanities Building, Room 210',
      day: 5,
      startSlot: 1,
      duration: 1,
      color: Color(0xFFF472B6),
    ),

    PlannerCourse(
      id: 'pe101',
      code: 'PE101',
      title: 'Physical Education',
      professor: 'Chang Yu Ming',
      credits: 1,
      type: 'PE',
      department: 'Physical Education',
      limit: 45,
      rating: 4.9,
      reviews: 52,
      midtermDate: 'None',
      finalDate: 'Dec 15',
      projectDate: 'None',
      grading: {'Participation': 70, 'Skill Test': 30},
      syllabus: ['Basic Training', 'Team Practice', 'Final Skill Test'],
      timeSlot: 'Wed 16:30 - 17:20',
      slotCode: 'W8',
      location: 'Gymnasium Court 2',
      day: 3,
      startSlot: 8,
      duration: 1,
      color: Color(0xFF34D399),
    ),

    PlannerCourse(
      id: 'lab205',
      code: 'LAB205',
      title: 'Software Studio Lab',
      professor: 'Wu Shane Lung',
      credits: 1,
      type: 'LAB',
      department: 'Computer Science',
      limit: 30,
      rating: 4.8,
      reviews: 41,
      midtermDate: 'Oct 25',
      finalDate: 'Dec 23',
      projectDate: 'Dec 12',
      grading: {'Projects': 70, 'Participation': 30},
      syllabus: ['Flutter Basics', 'Firebase Integration', 'Final App Demo'],
      timeSlot: 'Mon 18:30 - 20:20',
      slotCode: 'MaMb',
      location: 'CS Lab, Room 501',
      day: 1,
      startSlot: 10,
      duration: 2,
      color: Color(0xFF22C55E),
    ),

    PlannerCourse(
      id: 'phy101',
      code: 'PHY101',
      title: 'General Physics',
      professor: 'Liu Kai Wen',
      credits: 3,
      type: 'CORE',
      department: 'Physics',
      limit: 90,
      rating: 4.4,
      reviews: 73,
      midtermDate: 'Oct 21',
      finalDate: 'Dec 21',
      projectDate: 'None',
      grading: {'Exams': 80, 'Homework': 20},
      syllabus: ['Motion', 'Energy', 'Electricity'],
      timeSlot: 'Tue 10:10 - 12:00',
      slotCode: 'T3T4',
      location: 'Science Building, Room 102',
      day: 2,
      startSlot: 2,
      duration: 2,
      color: Color(0xFF38BDF8),
    ),

    PlannerCourse(
      id: 'chem101',
      code: 'CHEM101',
      title: 'General Chemistry',
      professor: 'Tsai Chia Yu',
      credits: 3,
      type: 'CORE',
      department: 'Chemistry',
      limit: 85,
      rating: 4.3,
      reviews: 69,
      midtermDate: 'Oct 19',
      finalDate: 'Dec 18',
      projectDate: 'None',
      grading: {'Exams': 70, 'Lab': 20, 'Participation': 10},
      syllabus: [
        'Atoms and Molecules',
        'Chemical Bonds',
        'Reaction Principles',
      ],
      timeSlot: 'Thu 09:00 - 09:50',
      slotCode: 'R2',
      location: 'Chemistry Building, Room 304',
      day: 4,
      startSlot: 1,
      duration: 1,
      color: Color(0xFFFB7185),
    ),

    PlannerCourse(
      id: 'econ101',
      code: 'ECON101',
      title: 'Introduction to Economics',
      professor: 'Kao Ming Jie',
      credits: 3,
      type: 'ELECTIVE',
      department: 'Economics',
      limit: 120,
      rating: 4.6,
      reviews: 101,
      midtermDate: 'Oct 16',
      finalDate: 'Dec 17',
      projectDate: 'None',
      grading: {'Exams': 60, 'Homework': 20, 'Participation': 20},
      syllabus: ['Supply and Demand', 'Market Structure', 'Economic Policy'],
      timeSlot: 'Fri 13:20 - 15:10',
      slotCode: 'F5F6',
      location: 'Management Building, Room 201',
      day: 5,
      startSlot: 5,
      duration: 2,
      color: Color(0xFFF97316),
    ),

    PlannerCourse(
      id: 'psy101',
      code: 'PSY101',
      title: 'Introduction to Psychology',
      professor: 'Hsu Pei Ling',
      credits: 2,
      type: 'GE',
      department: 'Psychology',
      limit: 70,
      rating: 4.7,
      reviews: 84,
      midtermDate: 'Oct 14',
      finalDate: 'Dec 14',
      projectDate: 'Dec 1',
      grading: {'Exams': 50, 'Projects': 30, 'Participation': 20},
      syllabus: [
        'Mind and Behavior',
        'Learning and Memory',
        'Social Psychology',
      ],
      timeSlot: 'Tue 16:30 - 18:20',
      slotCode: 'T8T9',
      location: 'Social Science Building, Room 110',
      day: 2,
      startSlot: 8,
      duration: 2,
      color: Color(0xFFC084FC),
    ),

    PlannerCourse(
      id: 'hist101',
      code: 'HIST101',
      title: 'World History',
      professor: 'Chou Wen An',
      credits: 2,
      type: 'GE',
      department: 'History',
      limit: 75,
      rating: 4.2,
      reviews: 48,
      midtermDate: 'Oct 13',
      finalDate: 'Dec 13',
      projectDate: 'Nov 28',
      grading: {'Exams': 50, 'Projects': 30, 'Participation': 20},
      syllabus: ['Ancient Civilizations', 'Modern History', 'Globalization'],
      timeSlot: 'Mon 15:30 - 17:20',
      slotCode: 'M7M8',
      location: 'Humanities Building, Room 305',
      day: 1,
      startSlot: 7,
      duration: 2,
      color: Color(0xFF818CF8),
    ),

    PlannerCourse(
      id: 'soc101',
      code: 'SOC101',
      title: 'Sociology',
      professor: 'Yang Shu Hui',
      credits: 2,
      type: 'ELECTIVE',
      department: 'Sociology',
      limit: 65,
      rating: 4.3,
      reviews: 37,
      midtermDate: 'Oct 22',
      finalDate: 'Dec 20',
      projectDate: 'Dec 6',
      grading: {'Exams': 40, 'Projects': 40, 'Participation': 20},
      syllabus: [
        'Social Structure',
        'Groups and Institutions',
        'Social Change',
      ],
      timeSlot: 'Wed 13:20 - 15:10',
      slotCode: 'W5W6',
      location: 'Social Science Building, Room 208',
      day: 3,
      startSlot: 5,
      duration: 2,
      color: Color(0xFF2DD4BF),
    ),

    PlannerCourse(
      id: 'art101',
      code: 'ART101',
      title: 'Introduction to Arts',
      professor: 'Lai Yu Ting',
      credits: 1,
      type: 'ELECTIVE',
      department: 'Arts',
      limit: 50,
      rating: 4.8,
      reviews: 42,
      midtermDate: 'None',
      finalDate: 'Dec 11',
      projectDate: 'Dec 4',
      grading: {'Projects': 70, 'Participation': 30},
      syllabus: ['Visual Elements', 'Art Appreciation', 'Creative Project'],
      timeSlot: 'Fri 15:30 - 16:20',
      slotCode: 'F7',
      location: 'Arts Center, Room 102',
      day: 5,
      startSlot: 7,
      duration: 1,
      color: Color(0xFFFACC15),
    ),

    PlannerCourse(
      id: 'phil101',
      code: 'PHIL101',
      title: 'Introduction to Philosophy',
      professor: 'Teng Li Wei',
      credits: 4,
      type: 'GE',
      department: 'Philosophy',
      limit: 55,
      rating: 4.5,
      reviews: 58,
      midtermDate: 'Oct 23',
      finalDate: 'Dec 24',
      projectDate: 'None',
      grading: {'Exams': 60, 'Homework': 20, 'Participation': 20},
      syllabus: ['Logic and Argument', 'Ethics', 'Knowledge and Reality'],
      timeSlot: 'Thu 15:30 - 17:20',
      slotCode: 'R7R8',
      location: 'Humanities Building, Room 406',
      day: 4,
      startSlot: 7,
      duration: 2,
      color: Color(0xFF9CA3AF),
    ),

    PlannerCourse(
      id: 'cs230',
      code: 'CS230',
      title: 'Hardware Design & Lab',
      professor: 'Lee Meng Jiao',
      credits: 2,
      type: 'LAB',
      department: 'Computer Science',
      limit: 60,
      rating: 4.9,
      reviews: 112,
      midtermDate: 'Oct 16',
      finalDate: 'Dec 19',
      projectDate: 'Dec 8',
      grading: {'Exams': 35, 'Projects': 45, 'Participation': 20},
      syllabus: [
        'Digital Hardware Basics',
        'FPGA Design',
        'Hardware Lab Project',
      ],
      timeSlot: 'Mon 10:10 - 12:00',
      slotCode: 'M3M4',
      location: 'Engineering Building, Lab 303',
      day: 1,
      startSlot: 2,
      duration: 2,
      color: Color(0xFFA855F7),
    ),
  ];