import 'dart:convert';
import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../utilities/data.dart';
import '../utilities/models.dart';

// ----------------------------------------------------------------------
// UPCOMING TASKS WIDGET (Now Stateful to load JSON!)
// ----------------------------------------------------------------------
class UpcomingTasksWidget extends StatefulWidget {
  final Function(AppEvent) onTaskTap;

  const UpcomingTasksWidget({
    Key? key,
    required this.onTaskTap, // 2. Require it here
  }) : super(key: key);

  @override
  State<UpcomingTasksWidget> createState() => _UpcomingTasksWidgetState();
}

class _UpcomingTasksWidgetState extends State<UpcomingTasksWidget> {
  List<AppEvent> _tasks = [];
  List<String> _completedTaskIds = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadTasksFromJson();
  }

  // Assign colors dynamically based on the AI's parsed type
  Color _getColorForType(String type) {
    switch (type.toLowerCase()) {
      case 'quiz':
        return Colors.red.shade400;
      case 'midterm':
      case 'final':
        return Colors.deepPurple;
      case 'homework':
        return Colors.blue.shade500;
      case 'project':
        return Colors.orange.shade500;
      default:
        return Colors.teal; // Fallback for "Other"
    }
  }

  // Load and parse the JSON file generated by your Python script
  Future<void> _loadTasksFromJson() async {
    try {
      final String response = await rootBundle.loadString('assets/upcoming_task.json');
      final List<dynamic> data = json.decode(response);

      List<AppEvent> parsedTasks = data.map((json) {
        DateTime parsedDate;
        try {
          parsedDate = DateTime.parse(json['dueDate']);
        } catch (e) {
          parsedDate = DateTime.now().add(const Duration(days: 1)); // Fallback if "TBD"
        }

        return AppEvent(
          id: json['id'] ?? UniqueKey().toString(),
          title: json['title'] ?? 'Unknown Task',
          
          // THE FIX: Check if it's null OR if it's an empty string after trimming spaces
          code: (json['code'] == null || json['code'].toString().trim().isEmpty) 
              ? 'NTHU' 
              : json['code'],
              
          time: json['time'] ?? '23:59',
          type: json['type'] ?? 'Other',
          color: _getColorForType(json['type'] ?? 'Other'),
          location: json['location'] ?? 'Online',
          progress: json['status'] == 'Completed' ? 100 : 0,
          dueDate: parsedDate,
        );
      }).toList();

      if (mounted) {
        setState(() {
          _tasks = parsedTasks;
          // Pre-fill completed tasks if any came from the JSON as completed
          _completedTaskIds = parsedTasks
              .where((t) => t.progress == 100)
              .map((t) => t.id)
              .toList();
          _isLoading = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _tasks = [];
          _isLoading = false;
        });
      }
    }
  }

  // Your original countdown logic
  String _formatCountdown(DateTime dueDate) {
    final now = DateTime.now();
    final deadline = DateTime(dueDate.year, dueDate.month, dueDate.day, 23, 59, 59);
    final diff = deadline.difference(now);

    if (diff.isNegative) return "Overdue";

    final weeks = diff.inDays ~/ 7;
    final days = diff.inDays % 7;
    final hours = diff.inHours % 24;

    List<String> parts = [];
    if (weeks > 0) parts.add("${weeks}W");
    if (days > 0) parts.add("${days}D");
    if (hours > 0 || parts.isEmpty) parts.add("${hours}H");

    return parts.join(" ");
  }

  // Handle the swipe-to-complete action
  void _toggleComplete(String taskId) {
    setState(() {
      if (_completedTaskIds.contains(taskId)) {
        _completedTaskIds.remove(taskId);
        // Optional: Reset progress to 0 when un-checking
        final index = _tasks.indexWhere((t) => t.id == taskId);
        if (index != -1) _tasks[index].progress = 0;
      } else {
        _completedTaskIds.add(taskId);
        // Optional: Set progress to 100 when checking
        final index = _tasks.indexWhere((t) => t.id == taskId);
        if (index != -1) _tasks[index].progress = 100;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    // Separate active and completed tasks so we can show active ones first
    final activeTasks = _tasks.where((t) => !_completedTaskIds.contains(t.id)).toList();
    final completedTasks = _tasks.where((t) => _completedTaskIds.contains(t.id)).toList();
    
    // Combine them (active at the top, completed at the bottom)
    final displayTasks = [...activeTasks, ...completedTasks];

    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 24),
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(40),
        border: Border.all(color: Colors.grey.shade100),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.02),
            blurRadius: 10,
            offset: const Offset(0, 4),
          )
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Row(
            children: [
              Container(
                width: 40,
                height: 40,
                decoration: BoxDecoration(
                  color: Colors.orange.shade50,
                  borderRadius: BorderRadius.circular(16),
                ),
                child: Icon(Icons.rocket_launch_rounded, color: Colors.orange.shade600, size: 20),
              ),
              const SizedBox(width: 12),
              const Text(
                "Upcoming",
                style: TextStyle(
                  fontSize: 20, 
                  fontWeight: FontWeight.w900,
                  color: Colors.black),
              ),
              const Spacer(),
              IconButton(
                icon: const Icon(Icons.swap_vert_rounded, color: nthuPurple),
                onPressed: () {
                  // Optional: Add sorting logic here later
                  _loadTasksFromJson(); // Refresh button!
                },
                style: IconButton.styleFrom(backgroundColor: Colors.grey.shade50),
              ),
            ],
          ),
          const SizedBox(height: 16),

          // List of Tasks
          if (_isLoading)
            const Center(
              child: Padding(
                padding: EdgeInsets.all(24.0),
                child: CircularProgressIndicator(color: Colors.orange),
              )
            )
          else if (displayTasks.isEmpty)
            Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 48),
              decoration: BoxDecoration(
                color: Colors.grey.shade50.withOpacity(0.5),
                borderRadius: BorderRadius.circular(32),
                border: Border.all(color: Colors.grey.shade100, style: BorderStyle.solid), 
              ),
              child: const Text(
                "NO MATCHING EVENTS",
                textAlign: TextAlign.center,
                style: TextStyle(fontSize: 10, fontWeight: FontWeight.w900, color: Colors.grey, letterSpacing: 1.5),
              ),
            )
          else
            ListView.separated(
              shrinkWrap: true,
              physics: const NeverScrollableScrollPhysics(),
              itemCount: displayTasks.length,
              separatorBuilder: (_, __) => const SizedBox(height: 12),
              itemBuilder: (context, index) {
                final task = displayTasks[index];
                final isCompleted = _completedTaskIds.contains(task.id);

                return _UpcomingTaskItem(
                  task: task,
                  isCompleted: isCompleted,
                  countdownStr: _formatCountdown(task.dueDate),
                  onToggleComplete: _toggleComplete,
                  onTaskTap: widget.onTaskTap,
                );
              },
            ),
        ],
      ),
    );
  }
}

// ----------------------------------------------------------------------
// TASK ITEM WIDGET (Unchanged from your code)
// ----------------------------------------------------------------------
class _UpcomingTaskItem extends StatefulWidget {
  final AppEvent task;
  final bool isCompleted;
  final String countdownStr;
  final Function(String) onToggleComplete;
  final Function(AppEvent) onTaskTap;

  const _UpcomingTaskItem({
    Key? key,
    required this.task,
    required this.isCompleted,
    required this.countdownStr,
    required this.onToggleComplete,
    required this.onTaskTap,
  }) : super(key: key);

  @override
  State<_UpcomingTaskItem> createState() => _UpcomingTaskItemState();
}

class _UpcomingTaskItemState extends State<_UpcomingTaskItem> {
  double _swipeProgress = 0.0;

  Widget _buildCelebrationWidget() {
    double burstProgress = ((_swipeProgress - 0.15) / 0.4).clamp(0.0, 1.0);
    double opacity = 1.0 - ((_swipeProgress - 0.7) / 0.3).clamp(0.0, 1.0);

    return SizedBox(
      width: 56,
      height: 56,
      child: Stack(
        alignment: Alignment.center,
        children: [
          if (_swipeProgress > 0.15)
            Opacity(
              opacity: opacity,
              child: CustomPaint(
                size: const Size(56, 56),
                painter: _ParticlePainter(progress: burstProgress),
              ),
            ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    Widget swipeBackground = Container(
      decoration: BoxDecoration(
        color: widget.isCompleted ? Colors.grey.shade300 : Colors.green,
        borderRadius: BorderRadius.circular(24),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Padding(
            padding: const EdgeInsets.only(left: 20),
            child: widget.isCompleted ? const SizedBox.shrink() : _buildCelebrationWidget(),
          ),
          Padding(
            padding: const EdgeInsets.only(right: 20),
            child: widget.isCompleted ? const SizedBox.shrink() : _buildCelebrationWidget(),
          ),
        ],
      ),
    );

    return ClipRRect(
      borderRadius: BorderRadius.circular(24),
      child: Dismissible(
        key: Key('${widget.task.id}_${widget.isCompleted}'),
        direction: DismissDirection.horizontal,
        onUpdate: (details) {
          setState(() {
            _swipeProgress = details.progress;
          });
        },
        onDismissed: (_) {
          widget.onToggleComplete(widget.task.id);
        },
        background: swipeBackground,
        secondaryBackground: swipeBackground,
        child: GestureDetector(
          onTap: () {
            if (!widget.isCompleted) widget.onTaskTap(widget.task);
          },
          child: AnimatedContainer(
            duration: const Duration(milliseconds: 300),
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.grey.shade50,
              borderRadius: BorderRadius.circular(24),
            ),
            foregroundDecoration: widget.isCompleted
                ? BoxDecoration(
                    color: Colors.white.withOpacity(0.5),
                    backgroundBlendMode: BlendMode.saturation,
                    borderRadius: BorderRadius.circular(24),
                  )
                : null,
            child: Row(
              children: [
                Container(
                  width: 6,
                  height: 60,
                  decoration: BoxDecoration(
                    color: widget.task.color,
                    borderRadius: BorderRadius.circular(4),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            widget.task.code.toUpperCase(),
                            style: TextStyle(
                              fontSize: 9,
                              fontWeight: FontWeight.w900,
                              letterSpacing: 1.5,
                              color: widget.isCompleted ? Colors.grey : nthuPurple.withOpacity(0.6),
                            ),
                          ),
                          if (!widget.isCompleted)
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                              decoration: BoxDecoration(
                                color: Colors.orange.shade50,
                                borderRadius: BorderRadius.circular(6),
                              ),
                              child: Text(
                                widget.countdownStr,
                                style: TextStyle(
                                  fontSize: 9,
                                  fontWeight: FontWeight.w900,
                                  letterSpacing: -0.5,
                                  color: Colors.orange.shade600,
                                ),
                              ),
                            )
                        ],
                      ),
                      const SizedBox(height: 4),
                      Text(
                        widget.task.title,
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        style: TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.bold,
                          color: widget.isCompleted ? Colors.grey : Colors.black87,
                          decoration: widget.isCompleted ? TextDecoration.lineThrough : null,
                        ),
                      ),
                      if (!widget.isCompleted) ...[
                        const SizedBox(height: 6),
                        Row(
                          children: [
                            Expanded(
                              child: ClipRRect(
                                borderRadius: BorderRadius.circular(4),
                                child: LinearProgressIndicator(
                                  value: widget.task.progress / 100,
                                  backgroundColor: Colors.grey.shade200,
                                  valueColor: AlwaysStoppedAnimation<Color>(widget.task.color),
                                  minHeight: 4,
                                ),
                              ),
                            ),
                            const SizedBox(width: 8),
                            Text(
                              "${widget.task.progress}%",
                              style: const TextStyle(fontSize: 8, fontWeight: FontWeight.w900, color: Colors.grey),
                            )
                          ],
                        )
                      ]
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

// ----------------------------------------------------------------------
// PARTICLE PAINTER (Unchanged from your code)
// ----------------------------------------------------------------------
class _ParticlePainter extends CustomPainter {
  final double progress;

  _ParticlePainter({required this.progress});

  @override
  void paint(Canvas canvas, Size size) {
    final center = Offset(size.width / 2, size.height / 2);
    final colors = [
      Colors.white, 
      Colors.yellowAccent, 
      Colors.pink.shade200, 
      Colors.cyanAccent, 
      Colors.orangeAccent, 
      Colors.white
    ];
    final paint = Paint()..style = PaintingStyle.fill;

    for (int i = 0; i < 6; i++) {
      final angle = (i * 60) * math.pi / 180;
      final distance = 14.0 + (progress * 28.0);
      final x = center.dx + distance * math.cos(angle);
      final y = center.dy + distance * math.sin(angle);

      paint.color = colors[i % colors.length];

      if (i % 2 == 0) {
        canvas.drawCircle(Offset(x, y), 3.0 + (1 - progress) * 2, paint);
      } else {
        canvas.save();
        canvas.translate(x, y);
        canvas.rotate(progress * math.pi * 2); 
        canvas.drawRect(Rect.fromCenter(center: Offset.zero, width: 6, height: 6), paint);
        canvas.restore();
      }
    }
  }

  @override
  bool shouldRepaint(covariant _ParticlePainter oldDelegate) => oldDelegate.progress != progress;
}